# Python is a terrible language for numerics!
* Python integers are actually an object with header and typing information
* access to Python integers requires a level of indirection
* In C, integers are directly accessible in memory without indirection
<img src="images/python-01.png" width=400 height=400>

## The Problem is Even Worse for Python Lists 
* Python lists are immensely flexible
  * no fixed size
  * OK to have heterogeneous data
* ...but as a result they are not likely to be contiguous in memory
* and even if they are, there is still a lot of indirection required
* ergo, they aren't good for fast number crunching
<img src="images/python-02.png" width=400 height=400>

## The Solution is to Use <a href="http://www.numpy.org">Numpy</a>
* written in C
* allows for vectorized operations

In [2]:
import numpy as np
np.random.seed(0)

# let's create a simple Python function which
# computes 1/x for a list of values
def compute_reciprocals(values):
    # first, create an empty numpy array
    output = np.empty(len(values))
    # now fill it...
    for i in range(len(values)):
        output[i] = 1.0 / values[i]

    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [ ]:
# Doing something like the above is super slow in Python
big_array = np.random.randint(1, 100, size=1_000_000)
%timeit compute_reciprocals(big_array)

## A numpy Array
* data is contiguous
<img src="images/python-03.png" width=300 height=300>

In [3]:
# numpy will intuit the data type
a = np.array([1, 4, 2, 5, 3])
a, a.dtype

(array([1, 4, 2, 5, 3]), dtype('int64'))

In [4]:
a = np.array([3.14, 4, 2, 3])
a, a.dtype

(array([3.14, 4.  , 2.  , 3.  ]), dtype('float64'))

In [ ]:
# ...or you can be explicit
a = np.array([1, 2, 3, 4], dtype='float32')
a

In [5]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.random((3, 3))

array([[0.4236548 , 0.64589411, 0.43758721],
       [0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456]])

In [14]:
np.random.randint(0, 10, (3, 3))

array([[5, 9, 8],
       [9, 4, 3],
       [0, 3, 5]])

In [17]:
magic_square = np.array([
    [16,  3,  2, 13],
    [ 5, 10, 11,  8],
    [ 9,  6,  7, 12],
    [ 4, 15, 14,  1]
])

In [33]:
# can we verify the above?

## Converting array types

In [ ]:
x = np.linspace(0, 10, 50)
x

In [ ]:
x.astype(int)

## Multi-dimensional Arrays

In [ ]:
x2 = np.random.randint(10, size=(3, 4))
x2

## True "matrix-style" indexing

In [ ]:
x2[0, 0]

In [ ]:
x2[2, 0]

In [ ]:
x2[2, -1]

In [ ]:
x2[0, 0] = 12
x2

In [ ]:
np.arange(0, 9).reshape(3, 3)

## Array Slicing

In [ ]:
x = np.arange(10)
x[:5]

In [ ]:
x[5:]

In [ ]:
x[4:7]

In [ ]:
x[::2]

In [ ]:
x[1::2]

In [ ]:
x[::-1]

In [ ]:
x[5::-2]

## Filtering 1-dimensional data

In [ ]:
x = np.array([ 1, 0, 5, 2, 1, 0, 8, 0, 0 ])

In [ ]:
np.nonzero(x)

In [ ]:
x[np.nonzero(x)]

In [ ]:
x[x < 3]

## Filtering 2-dimensional data

In [ ]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, -1, 0]])
x

In [ ]:
# produces two arrays, one with x coords, one with y coords
np.nonzero(x)

In [ ]:
x[np.nonzero(x)]

In [ ]:
np.transpose(np.nonzero(x))

## Multi-dimensional subarrays

In [ ]:
x2

In [ ]:
x2[:2, :3]

In [ ]:
x2[:, ::2]

In [ ]:
x2[::-1, ::-1]

In [ ]:
np.flip(np.flip(x2, axis=0), axis=1)

## Subarray Views

In [ ]:
x2, id(x2)

In [ ]:
x2_sub = x2[:2, :2]
x2_sub, id(x2_sub)

In [ ]:
x2_sub[0, 0] = 99
x2_sub

In [ ]:
x2 # changes x2 as well, since the subarray has references to the original

## Vectorized Operations

In [ ]:
big_array = np.random.randint(1, 100, size=1_000_000)

In [ ]:
%timeit 1.0 / big_array

In [ ]:
big_array = np.random.rand(1_000_000)
%timeit sum(big_array) # Python sum method (serial)
%timeit np.sum(big_array) # numpy sum method (vectorized)

## Universal Funcs (ufuncs)
* operates on ndarrays in an element-by-element fashion
* _vectorized_ wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs

In [ ]:
x = np.arange(9).reshape((3, 3))
2 ** x

In [ ]:
x = np.arange(4)
-(0.5 * x + 1) ** 2

| Operator | ufunc           | Description                         |
|----------|-----------------|-------------------------------------|
|   +      | np.add          | Addition (e.g., 1 + 1 = 2)          |
|   -      | np.subtract     | Subtraction (e.g., 3 - 2 = 1)       |
|   -      | np.negative     | Unary negation (e.g., -2)           |
|   *      | np.multiply     | Multiplication (e.g., 2 * 3 = 6)    |
|   /      | np.divide       | Division (e.g., 3 / 2 = 1.5)        |
|   //     | np.floor_divide | Floor division (e.g., 3 // 2 = 1)   |
|   **     | np.power        | Exponentiation (e.g., 2 ** 3 = 8)   |
|   %      | np.mod          | Modulus/remainder (e.g., 9 % 4 = 1) |

## Exponent and Logarithm ufuncs

In [ ]:
x = [1, 2, 3]
np.exp(x)

In [ ]:
np.exp2(x)

In [ ]:
np.power(3, x)

In [ ]:
np.log([1, np.e, 3])

In [ ]:
np.log2([1, 256, 65536])

In [ ]:
np.log10([1_000, 1_000_000, 10 ** 10])

## Aggregate ufuncs

In [ ]:
x = np.arange(1, 6)
np.add.reduce(x) # reduce to scalar via addition

In [ ]:
np.multiply.reduce(x)

In [ ]:
np.add.accumulate(x)

In [ ]:
np.multiply.accumulate(x)